obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.45, 0], [0, -0.45], [0.45, 0], [0, 0.45]]
#robot_radius: ir_of_robot
inflation_radius: 0.6

observation_sources: point_cloud_sensor

point_cloud_sensor: {data_type: PointCloud, topic: /voxel_cloud, marking: true, clearing: true}
